name: Deploy Laravel to cPanel

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy build to Laravel core
      - name: Deploy Build to Laravel Core
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./public/build/
          server-dir: /laravel/public/build/
          state-name: .ftp-deploy-sync-state.json

      # Deploy Laravel core
      - name: Deploy Core Laravel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /laravel/
          state-name: .ftp-deploy-sync-state.json
          exclude: |
            public/**
            node_modules/**
            .git/**
            .github/**
            tests/**
            storage/logs/**
            .env

      # Deploy public
      - name: Replace index.php for production
        run: cp public/index.production.php public/index.php

      - name: Deploy Public Folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./public/
          server-dir: /public_html/resonan/
          state-name: .ftp-deploy-sync-state.json
